name: test
on:
  push:
    branches: main
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout test repo
        uses: actions/checkout@v4
        with:
          repository: seanlaw/test
      - name: Set Up Pixi
        uses: prefix-dev/setup-pixi@v0.9.4
        with:
          pixi-version: v0.62.2
