name: test
on:
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Display Python Version
        run: python -c "import sys; print(sys.version)"
        shell: bash
      - name: Set Up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ '3.12' }}
      - name: Display Python Version
        run: python -c "import sys; print(sys.version)"
        shell: bash
      - name: Checkout STUMPY
        uses: actions/checkout@v4
        with:
          repository: stumpy-dev/stumpy
